#!/usr/bin/env python3
"""
generate-seed.py — algorithmic, deterministic seed generator for the
local VibeTradez stack. Emits a self-contained seed.sql that creates
the schema, populates ~1 year of realistic trades + EOD summaries +
auto-execution rows, and leaves today as an unsettled "morning picks"
day with three live holdings so the dashboard exercises the green/red
unrealized-P&L coloring on first boot.

Equity-walk semantics (mirrors src/internal/exec/selector.go on prod):
  - 3 ranked picks per trading day (rank 1..3).
  - Auto-executor fires one contract per rank, gated only by a
    $10/share per-contract premium cap. No greedy fill, no daily
    basket budget.
  - Open fill at 9:30 ET, close fill at 3:55 ET (intraday only).

Realism knobs:
  - Win rate ≈ 52% (slight edge after costs).
  - Per-trade P&L distribution: roughly N(+1%, 35%) on the contract
    return, fat-tailed via clipping to [-100%, +500%]. Means: lots of
    small wins/losses, occasional big wins, occasional total losses.
  - Symbol universe: 30 liquid option names mixing megacaps and
    high-vol small caps so the dashboard feels diverse.
  - US market holidays for the past year are excluded.

Determinism: the random seed is fixed below, so re-running this
script produces byte-identical seed.sql output. Edit the seed if you
want a different equity walk.

Usage:
    cd vibetradez.com/local && python3 generate-seed.py > seed.sql
"""

from __future__ import annotations

import datetime as dt
import json
import random
from typing import List

RNG = random.Random(20260508)

OUT_HEADER = """\
-- VibeTradez local development seed data
--
-- AUTO-GENERATED by generate-seed.py — do not hand-edit. Re-run that
-- script to refresh; the random seed is fixed so output is stable.
--
-- Contains a year of realistic equity-walk auto-execution history
-- plus today's pre-EOD state (three live holdings, no summaries yet)
-- so the dashboard, history, and trade-detail pages all render
-- meaningful data on a fresh local boot.

-- ─── Schema (mirrors internal/store/store.go migrate()) ──────────────────

CREATE TABLE IF NOT EXISTS trades (
    id SERIAL PRIMARY KEY,
    date TEXT NOT NULL,
    symbol TEXT NOT NULL,
    contract_type TEXT NOT NULL,
    strike_price DOUBLE PRECISION NOT NULL,
    expiration TEXT NOT NULL,
    dte INTEGER NOT NULL,
    estimated_price DOUBLE PRECISION NOT NULL,
    thesis TEXT NOT NULL DEFAULT '',
    sentiment_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    current_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    target_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    stop_loss DOUBLE PRECISION NOT NULL DEFAULT 0,
    risk_level TEXT NOT NULL DEFAULT '',
    catalyst TEXT NOT NULL DEFAULT '',
    mention_count INTEGER NOT NULL DEFAULT 0,
    rank INTEGER NOT NULL DEFAULT 0,
    score INTEGER NOT NULL DEFAULT 0,
    rationale TEXT NOT NULL DEFAULT '',
    model TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_trades_date ON trades(date);

CREATE TABLE IF NOT EXISTS summaries (
    id SERIAL PRIMARY KEY,
    date TEXT NOT NULL,
    symbol TEXT NOT NULL,
    contract_type TEXT NOT NULL,
    strike_price DOUBLE PRECISION NOT NULL,
    expiration TEXT NOT NULL,
    entry_price DOUBLE PRECISION NOT NULL,
    closing_price DOUBLE PRECISION NOT NULL,
    stock_open DOUBLE PRECISION NOT NULL,
    stock_close DOUBLE PRECISION NOT NULL,
    notes TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_summaries_date ON summaries(date);

CREATE TABLE IF NOT EXISTS executions (
    id SERIAL PRIMARY KEY,
    trade_id INTEGER REFERENCES trades(id),
    mode TEXT NOT NULL,
    side TEXT NOT NULL,
    schwab_order_id TEXT,
    status TEXT NOT NULL,
    fill_price DOUBLE PRECISION,
    filled_quantity INTEGER NOT NULL DEFAULT 0,
    requested_quantity INTEGER NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    filled_at TIMESTAMPTZ,
    error_message TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_executions_trade_id ON executions(trade_id);
CREATE INDEX IF NOT EXISTS idx_executions_open_pending
    ON executions(status) WHERE status IN ('pending','working');

CREATE TABLE IF NOT EXISTS subscribers (
    id SERIAL PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    active BOOLEAN NOT NULL DEFAULT true,
    auth_user_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    unsubscribed_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_subscribers_active ON subscribers(active);
CREATE INDEX IF NOT EXISTS idx_subscribers_auth_user_id ON subscribers(auth_user_id);

CREATE TABLE IF NOT EXISTS oauth_tokens (
    id SERIAL PRIMARY KEY,
    provider TEXT NOT NULL UNIQUE,
    access_token TEXT NOT NULL,
    refresh_token TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    refresh_token_issued_at TIMESTAMPTZ,
    reauth_nag_sent_on DATE,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sent_rollouts (
    slug TEXT PRIMARY KEY,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    recipient_count INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS transcripts (
    id SERIAL PRIMARY KEY,
    date TEXT NOT NULL,
    kind TEXT NOT NULL,
    model TEXT NOT NULL DEFAULT '',
    events JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (date, kind)
);
CREATE INDEX IF NOT EXISTS idx_transcripts_date ON transcripts(date);

TRUNCATE trades, summaries, executions, subscribers, sent_rollouts, transcripts RESTART IDENTITY;

INSERT INTO subscribers (email, name, active) VALUES
    ('local@vibetradez.local', 'Local Test', true),
    ('demo@example.com',       'Demo User',  true),
    ('jayce@vibetradez.local', 'Jayce',      true);

-- ─── Trades, summaries, and executions ───────────────────────────────────
"""

OUT_FOOTER = """
-- ─── End ──────────────────────────────────────────────────────────────────
"""

US_MARKET_HOLIDAYS_2025_2026 = {
    # 2025
    "2025-01-01", "2025-01-20", "2025-02-17", "2025-04-18",
    "2025-05-26", "2025-06-19", "2025-07-04", "2025-09-01",
    "2025-11-27", "2025-12-25",
    # 2026
    "2026-01-01", "2026-01-19", "2026-02-16", "2026-04-03",
    "2026-05-25",
}

SYMBOLS = [
    ("NVDA", 145.0), ("TSLA", 270.0), ("AAPL", 215.0), ("AMD", 165.0),
    ("META", 580.0), ("SPY", 555.0), ("QQQ", 480.0), ("MSFT", 415.0),
    ("GOOGL", 175.0), ("AMZN", 195.0), ("PLTR", 64.0), ("COIN", 240.0),
    ("GME", 23.0), ("HOOD", 28.0), ("SOFI", 12.5), ("RIVN", 11.0),
    ("LCID", 3.5), ("SHOP", 92.0), ("UBER", 78.0), ("SNAP", 9.5),
    ("BABA", 82.0), ("NFLX", 720.0), ("DIS", 105.0), ("BAC", 44.0),
    ("JPM", 222.0), ("BA", 175.0), ("F", 11.0), ("AKAM", 95.0),
    ("DDOG", 125.0), ("CRWD", 290.0),
]

CATALYSTS = [
    "Earnings report Friday morning", "AI keynote scheduled for tomorrow",
    "FDA approval decision pending", "Fed rate decision Wednesday",
    "Major product launch event",   "Analyst day presentation",
    "Short-interest squeeze potential", "Sector rotation tailwind",
    "Options expiry pinning", "Insider buying activity", "",
]

THESES = [
    "Strong technical setup with clean breakout above 50-day MA. Volume confirms momentum and IV is reasonably priced.",
    "Bullish flag forming on the daily chart. StockTwits mention count is accelerating with positive bias.",
    "Mean-reversion play targeting the lower bollinger band. Stock is oversold on RSI and the catalyst risk is well-defined.",
    "Directional bet on weekly options to capture the post-event move. Greeks favor the buyer with theta minimized.",
    "High-conviction sentiment shift. Multiple bullish posts in the last 24 hours with elevated engagement.",
    "Volatility crush trade post-earnings. The contract is priced for a larger move than historical realized vol suggests.",
    "Sector momentum setup. Peer stocks rallied on similar catalysts and this name is lagging the move.",
    "Defined-risk speculation on a low-probability but high-reward scenario. Sized for the conviction level.",
    "Short-dated gamma play. Favorable delta exposure for the expected move into tomorrow.",
    "Hedge against broader market exposure. Negative correlation expected if SPY breaks recent support.",
]

RATIONALES = [
    "Highest conviction pick of the day. Sentiment leans hard into this name and the chain shows favorable bid/ask spreads.",
    "Strong setup with a tight catalyst window. Sized at one contract; the move could happen fast at the open.",
    "Multiple confirming signals: trending score up, technicals clean, IV reasonable for the expected move.",
    "Solid second-tier idea. Sector tailwind supports the thesis and the entry premium leaves room for the exit.",
    "Speculative tail-risk play. Cheap premium and asymmetric upside; comfortable losing the entire premium.",
    "Mean-reversion candidate. Stock oversold on RSI; option premium prices in more downside than I expect.",
    "Earnings volatility play. Expected move priced in is smaller than historical move on similar setups.",
    "Sentiment-driven momentum. StockTwits is loud and the contract benefits from short-dated gamma.",
    "Hedge against broader exposure. Negative beta to SPY makes this a portfolio protection layer.",
    "Rounds out the three-pick basket as a directional play with a clean technical setup and contained downside.",
]


def trading_days(start: dt.date, end_inclusive: dt.date) -> List[dt.date]:
    """Yield weekdays in [start, end_inclusive] excluding US market holidays."""
    out: List[dt.date] = []
    d = start
    while d <= end_inclusive:
        if d.weekday() < 5 and d.isoformat() not in US_MARKET_HOLIDAYS_2025_2026:
            out.append(d)
        d += dt.timedelta(days=1)
    return out


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


def fmt_num(v: float, decimals: int = 2) -> str:
    return f"{v:.{decimals}f}"


def gen_pick(rank: int, day: dt.date) -> dict:
    """One pick at the given rank for the given day. Higher rank = lower
    conviction = lower score and slightly worse expected fill quality."""
    sym, base_stock = RNG.choice(SYMBOLS)
    contract_type = RNG.choices(["CALL", "PUT"], weights=[0.6, 0.4])[0]

    # Stock price drifts ±10% from baseline to add variety.
    stock_price = round(base_stock * RNG.uniform(0.9, 1.1), 2)

    # Strike near the money for realistic premiums.
    moneyness_offset = RNG.choice([-0.05, -0.025, 0.0, 0.025, 0.05])
    raw_strike = stock_price * (1 + moneyness_offset)
    strike = round_strike(raw_strike, stock_price)

    # DTE 1-7, weighted toward 2-4.
    dte = RNG.choices([1, 2, 3, 4, 5, 6, 7], weights=[1, 3, 4, 4, 2, 1, 1])[0]
    expiration = (day + dt.timedelta(days=dte)).isoformat()

    # Estimated premium $0.30 - $4.50 — well under the $10/share
    # per-contract cap so every pick is execution-eligible.
    estimated_price = round(RNG.uniform(0.3, 4.5), 2)

    # Score 5-9, anti-correlated with rank. The top-3 universe shouldn't
    # have anything weaker than ~5/10 conviction since the picker only
    # returns its best ideas.
    score = max(5, min(9, int(round(9 - (rank - 1) * 1.2 + RNG.gauss(0, 0.5)))))
    sentiment = round(RNG.uniform(-0.3, 0.85) * (1 if contract_type == "CALL" else -1), 2)
    mentions = RNG.randint(8, 220)

    target = round(estimated_price * RNG.uniform(1.4, 2.5), 2)
    stop = round(estimated_price * RNG.uniform(0.4, 0.7), 2)

    risk = "LOW" if score >= 8 else "MEDIUM" if score >= 6 else "HIGH"
    catalyst = RNG.choice(CATALYSTS)
    thesis = RNG.choice(THESES)
    rationale = RNG.choice(RATIONALES)

    return {
        "symbol": sym,
        "contract_type": contract_type,
        "strike": strike,
        "expiration": expiration,
        "dte": dte,
        "estimated_price": estimated_price,
        "stock_price": stock_price,
        "target": target,
        "stop": stop,
        "score": score,
        "sentiment": sentiment,
        "mentions": mentions,
        "risk": risk,
        "catalyst": catalyst,
        "thesis": thesis,
        "rationale": rationale,
        "rank": rank,
    }


def round_strike(strike: float, stock_price: float) -> float:
    """Round to a sensible options-chain strike spacing."""
    if stock_price < 25:
        step = 0.5
    elif stock_price < 200:
        step = 1.0
    else:
        step = 5.0
    return round(strike / step) * step


def simulate_close(estimated: float) -> float:
    """Return the closing premium for one contract given its open
    premium. Models a fat-tailed return distribution: roughly 52% win
    rate, mean return slightly positive, occasional total losses and
    occasional 3-5x winners."""
    # 8% chance of "total loss" (close ≈ 0.05 * entry) — the contract
    # decayed badly during the day.
    if RNG.random() < 0.08:
        return round(estimated * RNG.uniform(0.0, 0.15), 2)
    # 4% chance of "moonshot" (close 2.5-5x).
    if RNG.random() < 0.04:
        return round(estimated * RNG.uniform(2.5, 5.0), 2)
    # Otherwise normal-ish return centered slightly above 1.0.
    ret = RNG.gauss(1.02, 0.32)
    ret = max(0.10, min(2.5, ret))
    return round(estimated * ret, 2)


MODEL = "claude-opus-4-7"


def intent_otm_pct(p: dict) -> float:
    """Reconstruct the picker's signed-OTM intent (percent) from the
    seeded strike vs stock price."""
    stock = p["stock_price"]
    if stock <= 0:
        return 0.0
    return round(abs(p["strike"] - stock) / stock * 100, 1)


def quote_row(p: dict, *, post_open: bool) -> dict:
    """A realistic Schwab-style equity quote for one pick's symbol.
    post_open nudges the print slightly off the picker's pre-bell mark
    so the at-open agent's re-quote looks like a fresh tick."""
    last = round(p["stock_price"] * (RNG.uniform(0.998, 1.006) if post_open else 1.0), 2)
    spread = round(max(0.01, last * 0.0002), 2)
    open_px = round(p["stock_price"] * RNG.uniform(0.995, 1.005), 2)
    change = round(last - open_px, 2)
    return {
        "last_price": last,
        "bid": round(last - spread, 2),
        "ask": round(last + spread, 2),
        "open": open_px,
        "net_change": change,
        "net_change_pct": round((change / open_px) * 100, 2) if open_px else 0.0,
        "volume": RNG.randint(1_200_000, 48_000_000),
    }


def chain_excerpt(p: dict) -> dict:
    """A small live-chain excerpt around the chosen strike, with the
    picked contract's row priced near the seeded entry premium. Mirrors
    the shape schwab.OptionChain serializes (a few strikes with greeks
    + liquidity)."""
    step = 5.0 if p["stock_price"] >= 200 else (1.0 if p["stock_price"] >= 25 else 0.5)
    rows = []
    for k in (-step, 0.0, step):
        strike = round(p["strike"] + k, 2)
        # The chosen strike (k==0) is priced at ~the seeded entry; the
        # neighbors drift from it so the agent has a real choice.
        base = p["estimated_price"] * (1.0 if k == 0 else RNG.uniform(0.6, 1.5))
        mark = round(base, 2)
        spread = round(max(0.02, mark * 0.04), 2)
        rows.append({
            "strike": strike,
            "bid": round(mark - spread, 2),
            "ask": round(mark + spread, 2),
            "mark": mark,
            "delta": round(RNG.uniform(0.25, 0.6) * (1 if p["contract_type"] == "CALL" else -1), 3),
            "theta": round(-RNG.uniform(0.02, 0.12), 3),
            "open_interest": RNG.randint(400, 22_000),
            "volume": RNG.randint(60, 9_000),
        })
    return {
        "symbol": p["symbol"],
        "contract_type": p["contract_type"],
        "expiration": p["expiration"],
        "contracts": rows,
    }


def ev(round_no: int, etype: str, **kw) -> dict:
    """Build one transcript event dict matching transcript.Event JSON.
    tool_result values are stored as STRINGS (that's what the Go loop
    threads back), so dict results are json-encoded here."""
    e = {"round": round_no, "type": etype}
    if "text" in kw:
        e["text"] = kw["text"]
    if "tool_name" in kw:
        e["tool_name"] = kw["tool_name"]
    if "tool_use_id" in kw:
        e["tool_use_id"] = kw["tool_use_id"]
    if "tool_input" in kw:
        e["tool_input"] = kw["tool_input"]
    if "tool_result" in kw:
        r = kw["tool_result"]
        e["tool_result"] = r if isinstance(r, str) else json.dumps(r)
    return e


def build_selection_events(picks: List[dict], date_str: str) -> List[dict]:
    """The 9:25 ET picker conversation: read the trending tape, re-quote
    candidates against live equities, sanity-check liquidity, and commit
    to three symbols + contract intent. No strikes are priced pre-bell
    (options don't trade pre-market) — that's deliberate."""
    syms = ", ".join(f"${p['symbol']}" for p in picks)
    events: List[dict] = []
    events.append(ev(0, "text", text=(
        f"Pre-bell scan for {date_str}. I pulled the overnight trending tape across StockTwits, "
        f"Yahoo, Finviz and EDGAR, and the names carrying the most flow into the open are "
        f"{syms}. Listed options don't trade pre-market and Schwab's chain still shows "
        f"yesterday's 4pm close, so at 9:25 I only commit to ticker, direction and contract "
        f"intent — the actual strike gets chosen against the live chain at 9:30. Let me re-quote "
        f"the underlyings first.")))
    quote_payload = {p["symbol"]: quote_row(p, post_open=False) for p in picks}
    events.append(ev(0, "tool_use", tool_name="get_stock_quotes", tool_use_id="toolu_sel_quotes",
                     tool_input={"symbols": ",".join(p["symbol"] for p in picks)}))
    events.append(ev(0, "tool_result", tool_name="get_stock_quotes", tool_use_id="toolu_sel_quotes",
                     tool_result=quote_payload))

    top = picks[0]
    events.append(ev(1, "text", text=(
        f"Quotes line up with the tape. ${top['symbol']} is my highest-conviction name — "
        f"{top['thesis'][:140].rstrip('. ')}. Before I lock it in I want to confirm the weekly "
        f"chain is liquid enough to actually fill one contract at the open, so I'll glance at the "
        f"{top['symbol']} chain for open interest and spreads (not for pricing — that's stale "
        f"pre-bell).")))
    events.append(ev(1, "tool_use", tool_name="get_option_chain", tool_use_id="toolu_sel_chain",
                     tool_input={
                         "symbol": top["symbol"],
                         "contract_type": top["contract_type"],
                         "from_date": date_str,
                         "to_date": top["expiration"],
                     }))
    events.append(ev(1, "tool_result", tool_name="get_option_chain", tool_use_id="toolu_sel_chain",
                     tool_result=chain_excerpt(top)))

    lines = []
    for p in picks:
        lines.append(
            f"#{p['rank']} ${p['symbol']} {p['contract_type']} — ~{intent_otm_pct(p)}% OTM, "
            f">={max(1, p['dte'] - 1)} DTE, conviction {p['score']}/10")
    events.append(ev(2, "text", text=(
        "Liquidity checks out — tight enough spreads and healthy open interest on the front weeklies. "
        "Locking in the three-name basket:\n\n" + "\n".join(lines) + "\n\n"
        "Each is one contract, conviction expressed by which names I take rather than by sizing up. "
        "Emitting the ranked JSON now; the at-open agent will price the contracts at 9:30.")))
    return events


def build_execution_events(picks: List[dict], fills: "dict[int, float]", date_str: str) -> List[dict]:
    """The 9:30:00 ET at-open agent: chain is live, re-quote, walk each
    candidate's chain, check funds once (balance redacted), and fire one
    contract per name. Mirrors the real execagent tool surface."""
    events: List[dict] = []
    head = ", ".join(f"${p['symbol']} {p['contract_type']}" for p in picks)
    events.append(ev(0, "text", text=(
        f"9:30:00 ET — the bell rang and the chain is live. Three candidates from the 9:25 picker: "
        f"{head}. I'll re-quote the underlyings on the opening prints, then walk each live chain, "
        f"snap a strike near the intended OTM band, and fire exactly one contract per name whose "
        f"setup still holds.")))
    events.append(ev(0, "tool_use", tool_name="get_stock_quotes", tool_use_id="toolu_exec_quotes",
                     tool_input={"symbols": ",".join(p["symbol"] for p in picks)}))
    events.append(ev(0, "tool_result", tool_name="get_stock_quotes", tool_use_id="toolu_exec_quotes",
                     tool_result={p["symbol"]: quote_row(p, post_open=True) for p in picks}))

    rnd = 1
    for idx, p in enumerate(picks):
        r = p["rank"]
        fill = float(fills.get(r) or round(p["estimated_price"] * 1.01, 2))
        limit = round(min(10.0, fill * 1.10), 2)
        ask = round(fill * 1.03, 2)
        events.append(ev(rnd, "text", text=(
            f"Rank {r}: ${p['symbol']} {p['contract_type']}. Opening print is around "
            f"${p['stock_price']:.2f} and the intent was ~{intent_otm_pct(p)}% OTM at >="
            f"{max(1, p['dte'] - 1)} DTE. Pulling the live {p['symbol']} chain to find the strike.")))
        events.append(ev(rnd, "tool_use", tool_name="get_option_chain",
                         tool_use_id=f"toolu_exec_chain_{r}",
                         tool_input={
                             "symbol": p["symbol"],
                             "contract_type": p["contract_type"],
                             "from_date": date_str,
                             "to_date": p["expiration"],
                         }))
        events.append(ev(rnd, "tool_result", tool_name="get_option_chain",
                         tool_use_id=f"toolu_exec_chain_{r}", tool_result=chain_excerpt(p)))
        rnd += 1

        # Check funds once, on the first pick. The balance is redacted at
        # capture time — this is exactly what the stored transcript shows.
        if idx == 0:
            events.append(ev(rnd, "tool_use", tool_name="get_account_funds",
                             tool_use_id="toolu_exec_funds", tool_input={}))
            events.append(ev(rnd, "tool_result", tool_name="get_account_funds",
                             tool_use_id="toolu_exec_funds",
                             tool_result={"available_usd": "[redacted]", "currency": "USD"}))
            events.append(ev(rnd, "text", text=(
                "Settlement headroom is fine (balance redacted in the public transcript), and one "
                "contract is never the binding constraint anyway. Proceeding.")))
            rnd += 1

        events.append(ev(rnd, "text", text=(
            f"The ${p['strike']:.2f} {p['expiration']} {p['contract_type'].lower()} is sitting right in "
            f"the OTM band with a ~${ask:.2f} ask and healthy open interest. Taking one contract at a "
            f"${limit:.2f} limit (~1.1x the ask) so it fills into the opening liquidity.")))
        events.append(ev(rnd, "tool_use", tool_name="place_options_order",
                         tool_use_id=f"toolu_exec_order_{r}",
                         tool_input={
                             "rank": r,
                             "symbol": p["symbol"],
                             "contract_type": p["contract_type"],
                             "strike": p["strike"],
                             "expiration": p["expiration"],
                             "limit_price": limit,
                         }))
        events.append(ev(rnd, "tool_result", tool_name="place_options_order",
                         tool_use_id=f"toolu_exec_order_{r}",
                         tool_result={
                             "ok": True,
                             "order_id": f"100{RNG.randint(2_000_000, 9_999_999)}",
                             "rank": r,
                             "symbol": p["symbol"],
                             "strike": p["strike"],
                             "expiration": p["expiration"],
                             "limit_price": limit,
                             "quantity": 1,
                             "contract_type": p["contract_type"],
                             "orders_placed": idx + 1,
                             "orders_left": len(picks) - (idx + 1),
                         }))
        rnd += 1

    names = ", ".join(f"${p['symbol']}" for p in picks)
    events.append(ev(rnd, "text", text=(
        "Basket is in. Fired one contract on each of " + names + " — every setup held into the open, "
        "so no skips today. Orders are working as LIMITs; the reconcile cron will flip fills and the "
        "9:35 sweep cancels anything still resting. Done.")))
    return events


def main() -> None:
    today = dt.date(2026, 5, 15)
    start = today - dt.timedelta(days=365)
    days = trading_days(start, today)

    print(OUT_HEADER)

    trade_id_counter = 0
    execution_id_counter = 0
    trade_inserts: List[str] = []
    summary_inserts: List[str] = []
    execution_inserts: List[str] = []

    # Today's picks + the actual open-fill prices, captured so the
    # seeded selection/execution transcripts reference the exact same
    # contracts the dashboard shows holding.
    today_picks: List[dict] = []
    today_fills: "dict[int, float]" = {}

    per_contract_cap_usd = 10.0
    picks_per_day = 3

    for day in days:
        is_today = day == today
        date_str = day.isoformat()

        # Mirror the picker prompt's "every pick must be a different
        # ticker" rule. Regenerate any pick whose symbol already shows
        # up in today's basket; cap at 50 retries so a (hypothetically)
        # exhausted symbol universe doesn't loop forever.
        picks: List[dict] = []
        seen_symbols: set[str] = set()
        for rank in range(1, picks_per_day + 1):
            p = gen_pick(rank=rank, day=day)
            for _ in range(50):
                if p["symbol"] not in seen_symbols:
                    break
                p = gen_pick(rank=rank, day=day)
            picks.append(p)
            seen_symbols.add(p["symbol"])

        if is_today:
            today_picks = picks

        # Auto-executor: every pick whose premium fits the per-contract cap
        # fires. No greedy fill, no basket budget.
        executed_ranks: List[int] = []
        for p in picks:
            if p["estimated_price"] > per_contract_cap_usd:
                continue
            executed_ranks.append(p["rank"])

        # Insert all 3 trade rows.
        day_trade_ids = []
        for p in picks:
            trade_id_counter += 1
            day_trade_ids.append(trade_id_counter)
            trade_inserts.append(
                "({tid}, '{date}', '{sym}', '{ct}', {strike}, '{exp}', {dte}, "
                "{est}, '{thesis}', {senti}, {stock}, {tgt}, {stop}, '{risk}', "
                "'{cat}', {mentions}, {rank}, {score}, '{rat}', 'claude-opus-4-7')".format(
                    tid=trade_id_counter,
                    date=date_str,
                    sym=p["symbol"],
                    ct=p["contract_type"],
                    strike=fmt_num(p["strike"]),
                    exp=p["expiration"],
                    dte=p["dte"],
                    est=fmt_num(p["estimated_price"]),
                    thesis=sql_escape(p["thesis"]),
                    senti=fmt_num(p["sentiment"], 3),
                    stock=fmt_num(p["stock_price"]),
                    tgt=fmt_num(p["target"]),
                    stop=fmt_num(p["stop"]),
                    risk=p["risk"],
                    cat=sql_escape(p["catalyst"]),
                    mentions=p["mentions"],
                    rank=p["rank"],
                    score=p["score"],
                    rat=sql_escape(p["rationale"]),
                )
            )

            # Summaries on every day except today.
            if not is_today:
                close_p = simulate_close(p["estimated_price"])
                stock_move = RNG.gauss(0, 0.018)
                stock_close = round(p["stock_price"] * (1 + stock_move), 2)
                summary_inserts.append(
                    "('{date}', '{sym}', '{ct}', {strike}, '{exp}', {entry}, "
                    "{close}, {sopen}, {sclose}, '')".format(
                        date=date_str, sym=p["symbol"], ct=p["contract_type"],
                        strike=fmt_num(p["strike"]), exp=p["expiration"],
                        entry=fmt_num(p["estimated_price"]),
                        close=fmt_num(close_p),
                        sopen=fmt_num(p["stock_price"]),
                        sclose=fmt_num(stock_close),
                    )
                )

        # Executions: open + close pair per executed rank.
        # Today's executions stay in 'holding' state so the new
        # green/red unrealized-P&L coloring activates on first boot.
        # Today is always live mode so the user sees real-position UX.
        for rank in executed_ranks:
            p = picks[rank - 1]
            tid = day_trade_ids[rank - 1]
            mode = "live" if is_today else RNG.choices(["live", "paper"], weights=[0.6, 0.4])[0]
            entry_fill = round(p["estimated_price"] * RNG.uniform(0.97, 1.03), 2)
            if is_today:
                today_fills[rank] = entry_fill

            # OPEN side
            execution_id_counter += 1
            open_status = "filled"
            open_side_filled_at = f"'{date_str} 13:32:00+00'"  # ~9:32 ET
            execution_inserts.append(
                "({tid}, '{mode}', 'open', '{order}', '{status}', "
                "{fill}, 1, 1, '{date} 13:30:00+00', {filled_at}, '', "
                "'{date} 13:30:00+00')".format(
                    tid=tid, mode=mode, order=f"local-open-{execution_id_counter}",
                    status=open_status, fill=fmt_num(entry_fill),
                    date=date_str, filled_at=open_side_filled_at,
                )
            )

            # CLOSE side — present for past days only.
            if not is_today:
                execution_id_counter += 1
                close_p = simulate_close(p["estimated_price"])
                close_fill = round(close_p * RNG.uniform(0.97, 1.03), 2)
                execution_inserts.append(
                    "({tid}, '{mode}', 'close', '{order}', 'filled', "
                    "{fill}, 1, 1, '{date} 19:55:00+00', '{date} 19:56:00+00', '', "
                    "'{date} 19:55:00+00')".format(
                        tid=tid, mode=mode, order=f"local-close-{execution_id_counter}",
                        fill=fmt_num(close_fill), date=date_str,
                    )
                )

    # One big INSERT per table — Postgres handles thousands of rows in
    # a single statement without issue, and avoiding chunking keeps the
    # generator boring.
    if trade_inserts:
        print("INSERT INTO trades (id, date, symbol, contract_type, strike_price, expiration, dte, estimated_price, thesis, sentiment_score, current_price, target_price, stop_loss, risk_level, catalyst, mention_count, rank, score, rationale, model) VALUES")
        print(",\n".join(trade_inserts) + ";\n")

    if summary_inserts:
        print("INSERT INTO summaries (date, symbol, contract_type, strike_price, expiration, entry_price, closing_price, stock_open, stock_close, notes) VALUES")
        print(",\n".join(summary_inserts) + ";\n")

    if execution_inserts:
        print("INSERT INTO executions (trade_id, mode, side, schwab_order_id, status, fill_price, requested_quantity, filled_quantity, submitted_at, filled_at, error_message, created_at) VALUES")
        print(",\n".join(execution_inserts) + ";\n")

    # ─── Transcripts ─────────────────────────────────────────────────────
    # Realistic 9:25 selection + 9:30 execution conversations for today,
    # referencing the exact three picks the dashboard shows holding. The
    # execution transcript includes a get_account_funds call whose balance
    # is already redacted, exactly as the production capture path stores it.
    if today_picks:
        today_str = today.isoformat()
        transcript_rows = []
        for kind, events in (
            ("selection", build_selection_events(today_picks, today_str)),
            ("execution", build_execution_events(today_picks, today_fills, today_str)),
        ):
            events_json = sql_escape(json.dumps(events))
            transcript_rows.append(
                f"('{today_str}', '{kind}', '{MODEL}', '{events_json}'::jsonb)"
            )
        print("INSERT INTO transcripts (date, kind, model, events) VALUES")
        print(",\n".join(transcript_rows) + ";\n")

    # Re-sync the SERIAL sequences past the explicit IDs we inserted on
    # trades so future inserts don't collide. Other tables didn't get
    # explicit IDs, so nextval is already correct.
    print(f"SELECT setval(pg_get_serial_sequence('trades', 'id'), {trade_id_counter}, true);")

    print(OUT_FOOTER)


if __name__ == "__main__":
    main()
