#!/usr/bin/env python3
"""
generate-seed.py — algorithmic, deterministic seed generator for the
local VibeTradez stack. Emits a self-contained seed.sql that creates
the schema, populates ~1 year of realistic trades + EOD summaries +
auto-execution rows, and leaves today as an unsettled "morning picks"
day with three live holdings so the dashboard exercises the green/red
unrealized-P&L coloring on first boot.

Equity-walk semantics (mirrors src/internal/exec/selector.go on prod):
  - 10 ranked picks per trading day (rank 1..10).
  - Auto-executor walks ranks 1, 2, 3 in order and buys each whose
    estimated_price * 100 fits in the remaining $500 daily basket
    budget. Anything that doesn't fit is skipped.
  - Open fill at 9:30 ET, close fill at 3:55 ET (intraday only).
  - Per-contract premium capped at $5/share (max $500/contract).

Realism knobs:
  - Win rate ≈ 52% (slight edge after costs).
  - Per-trade P&L distribution: roughly N(+1%, 35%) on the contract
    return, fat-tailed via clipping to [-100%, +500%]. Means: lots of
    small wins/losses, occasional big wins, occasional total losses.
  - Symbol universe: 30 liquid option names mixing megacaps and
    high-vol small caps so the dashboard feels diverse.
  - US market holidays for the past year are excluded.

Determinism: the random seed is fixed below, so re-running this
script produces byte-identical seed.sql output. Edit the seed if you
want a different equity walk.

Usage:
    cd vibetradez.com/local && python3 generate-seed.py > seed.sql
"""

from __future__ import annotations

import datetime as dt
import random
from typing import List, Tuple

RNG = random.Random(20260508)

OUT_HEADER = """\
-- VibeTradez local development seed data
--
-- AUTO-GENERATED by generate-seed.py — do not hand-edit. Re-run that
-- script to refresh; the random seed is fixed so output is stable.
--
-- Contains a year of realistic equity-walk auto-execution history
-- plus today's pre-EOD state (three live holdings, no summaries yet)
-- so the dashboard, history, and trade-detail pages all render
-- meaningful data on a fresh local boot.

-- ─── Schema (mirrors internal/store/store.go migrate()) ──────────────────

CREATE TABLE IF NOT EXISTS trades (
    id SERIAL PRIMARY KEY,
    date TEXT NOT NULL,
    symbol TEXT NOT NULL,
    contract_type TEXT NOT NULL,
    strike_price DOUBLE PRECISION NOT NULL,
    expiration TEXT NOT NULL,
    dte INTEGER NOT NULL,
    estimated_price DOUBLE PRECISION NOT NULL,
    thesis TEXT NOT NULL DEFAULT '',
    sentiment_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    current_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    target_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    stop_loss DOUBLE PRECISION NOT NULL DEFAULT 0,
    risk_level TEXT NOT NULL DEFAULT '',
    catalyst TEXT NOT NULL DEFAULT '',
    mention_count INTEGER NOT NULL DEFAULT 0,
    rank INTEGER NOT NULL DEFAULT 0,
    score INTEGER NOT NULL DEFAULT 0,
    rationale TEXT NOT NULL DEFAULT '',
    model TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_trades_date ON trades(date);

CREATE TABLE IF NOT EXISTS summaries (
    id SERIAL PRIMARY KEY,
    date TEXT NOT NULL,
    symbol TEXT NOT NULL,
    contract_type TEXT NOT NULL,
    strike_price DOUBLE PRECISION NOT NULL,
    expiration TEXT NOT NULL,
    entry_price DOUBLE PRECISION NOT NULL,
    closing_price DOUBLE PRECISION NOT NULL,
    stock_open DOUBLE PRECISION NOT NULL,
    stock_close DOUBLE PRECISION NOT NULL,
    notes TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_summaries_date ON summaries(date);

CREATE TABLE IF NOT EXISTS executions (
    id SERIAL PRIMARY KEY,
    trade_id INTEGER,
    mode TEXT NOT NULL,
    side TEXT NOT NULL,
    schwab_order_id TEXT,
    status TEXT NOT NULL,
    fill_price DOUBLE PRECISION,
    filled_quantity INTEGER NOT NULL DEFAULT 0,
    requested_quantity INTEGER NOT NULL,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    filled_at TIMESTAMPTZ,
    error_message TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_executions_trade_id ON executions(trade_id);
CREATE INDEX IF NOT EXISTS idx_executions_open_pending
    ON executions(status) WHERE status IN ('pending','working');

CREATE TABLE IF NOT EXISTS subscribers (
    id SERIAL PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    unsubscribed_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_subscribers_active ON subscribers(active);

CREATE TABLE IF NOT EXISTS oauth_tokens (
    id SERIAL PRIMARY KEY,
    provider TEXT NOT NULL UNIQUE,
    access_token TEXT NOT NULL,
    refresh_token TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sent_rollouts (
    slug TEXT PRIMARY KEY,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    recipient_count INTEGER NOT NULL
);

TRUNCATE trades, summaries, executions, subscribers, sent_rollouts RESTART IDENTITY;

INSERT INTO subscribers (email, name, active) VALUES
    ('local@vibetradez.local', 'Local Test', true),
    ('demo@example.com',       'Demo User',  true),
    ('jayce@vibetradez.local', 'Jayce',      true);

-- ─── Trades, summaries, and executions ───────────────────────────────────
"""

OUT_FOOTER = """
-- ─── End ──────────────────────────────────────────────────────────────────
"""

US_MARKET_HOLIDAYS_2025_2026 = {
    # 2025
    "2025-01-01", "2025-01-20", "2025-02-17", "2025-04-18",
    "2025-05-26", "2025-06-19", "2025-07-04", "2025-09-01",
    "2025-11-27", "2025-12-25",
    # 2026
    "2026-01-01", "2026-01-19", "2026-02-16", "2026-04-03",
    "2026-05-25",
}

SYMBOLS = [
    ("NVDA", 145.0), ("TSLA", 270.0), ("AAPL", 215.0), ("AMD", 165.0),
    ("META", 580.0), ("SPY", 555.0), ("QQQ", 480.0), ("MSFT", 415.0),
    ("GOOGL", 175.0), ("AMZN", 195.0), ("PLTR", 64.0), ("COIN", 240.0),
    ("GME", 23.0), ("HOOD", 28.0), ("SOFI", 12.5), ("RIVN", 11.0),
    ("LCID", 3.5), ("SHOP", 92.0), ("UBER", 78.0), ("SNAP", 9.5),
    ("BABA", 82.0), ("NFLX", 720.0), ("DIS", 105.0), ("BAC", 44.0),
    ("JPM", 222.0), ("BA", 175.0), ("F", 11.0), ("AKAM", 95.0),
    ("DDOG", 125.0), ("CRWD", 290.0),
]

CATALYSTS = [
    "Earnings report Friday morning", "AI keynote scheduled for tomorrow",
    "FDA approval decision pending", "Fed rate decision Wednesday",
    "Major product launch event",   "Analyst day presentation",
    "Short-interest squeeze potential", "Sector rotation tailwind",
    "Options expiry pinning", "Insider buying activity", "",
]

THESES = [
    "Strong technical setup with clean breakout above 50-day MA. Volume confirms momentum and IV is reasonably priced.",
    "Bullish flag forming on the daily chart. StockTwits mention count is accelerating with positive bias.",
    "Mean-reversion play targeting the lower bollinger band. Stock is oversold on RSI and the catalyst risk is well-defined.",
    "Directional bet on weekly options to capture the post-event move. Greeks favor the buyer with theta minimized.",
    "High-conviction sentiment shift. Multiple bullish posts in the last 24 hours with elevated engagement.",
    "Volatility crush trade post-earnings. The contract is priced for a larger move than historical realized vol suggests.",
    "Sector momentum setup. Peer stocks rallied on similar catalysts and this name is lagging the move.",
    "Defined-risk speculation on a low-probability but high-reward scenario. Sized for the conviction level.",
    "Short-dated gamma play. Favorable delta exposure for the expected move into tomorrow.",
    "Hedge against broader market exposure. Negative correlation expected if SPY breaks recent support.",
]

RATIONALES = [
    "Highest conviction pick of the day. Sentiment leans hard into this name and the chain shows favorable bid/ask spreads.",
    "Strong setup but the catalyst window is tight. Sized smaller because the move could happen pre-market.",
    "Multiple confirming signals: trending score up, technicals clean, IV reasonable for the expected move.",
    "Decent risk/reward but not top-tier. Including because the broader sector tailwind supports the thesis.",
    "Speculative tail-risk play. Cheap premium and asymmetric upside; comfortable losing the entire premium.",
    "Mean-reversion candidate. Stock oversold on RSI; option premium prices in more downside than I expect.",
    "Earnings volatility play. Expected move priced in is smaller than historical move on similar setups.",
    "Sentiment-driven momentum. StockTwits is loud and the contract benefits from short-dated gamma.",
    "Hedge against broader exposure. Negative beta to SPY makes this a portfolio protection layer.",
    "Lowest-ranked pick. Including for diversification but conviction is the weakest of the day.",
]


def trading_days(start: dt.date, end_inclusive: dt.date) -> List[dt.date]:
    """Yield weekdays in [start, end_inclusive] excluding US market holidays."""
    out: List[dt.date] = []
    d = start
    while d <= end_inclusive:
        if d.weekday() < 5 and d.isoformat() not in US_MARKET_HOLIDAYS_2025_2026:
            out.append(d)
        d += dt.timedelta(days=1)
    return out


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


def fmt_num(v: float, decimals: int = 2) -> str:
    return f"{v:.{decimals}f}"


def gen_pick(rank: int, day: dt.date) -> dict:
    """One pick at the given rank for the given day. Higher rank = lower
    conviction = lower score and slightly worse expected fill quality."""
    sym, base_stock = RNG.choice(SYMBOLS)
    contract_type = RNG.choices(["CALL", "PUT"], weights=[0.6, 0.4])[0]

    # Stock price drifts ±10% from baseline to add variety.
    stock_price = round(base_stock * RNG.uniform(0.9, 1.1), 2)

    # Strike near the money for realistic premiums.
    moneyness_offset = RNG.choice([-0.05, -0.025, 0.0, 0.025, 0.05])
    raw_strike = stock_price * (1 + moneyness_offset)
    strike = round_strike(raw_strike, stock_price)

    # DTE 1-7, weighted toward 2-4.
    dte = RNG.choices([1, 2, 3, 4, 5, 6, 7], weights=[1, 3, 4, 4, 2, 1, 1])[0]
    expiration = (day + dt.timedelta(days=dte)).isoformat()

    # Estimated premium $0.30 - $4.50 — must be ≤ $5/share to be eligible
    # for auto-execution per server-side per-contract cap.
    estimated_price = round(RNG.uniform(0.3, 4.5), 2)
    # Special case: today's top-3 picks get cheaper premiums so the
    # equity-walk basket actually picks all three (rather than blowing
    # through the $500 cap on rank-1 alone). Keeps the dashboard demo
    # showing 3 holding cards with the new green/red coloring on first
    # boot. Past days stay random.
    if day == dt.date(2026, 5, 8) and rank <= 3:
        estimated_price = round(RNG.uniform(0.7, 1.5), 2)

    # Score 4-9, anti-correlated with rank.
    score = max(2, min(9, int(round(9 - (rank - 1) * 0.6 + RNG.gauss(0, 0.6)))))
    sentiment = round(RNG.uniform(-0.3, 0.85) * (1 if contract_type == "CALL" else -1), 2)
    mentions = RNG.randint(8, 220)

    target = round(estimated_price * RNG.uniform(1.4, 2.5), 2)
    stop = round(estimated_price * RNG.uniform(0.4, 0.7), 2)

    risk = "LOW" if score >= 8 else "MEDIUM" if score >= 6 else "HIGH"
    catalyst = RNG.choice(CATALYSTS)
    thesis = RNG.choice(THESES)
    rationale = RNG.choice(RATIONALES)

    return {
        "symbol": sym,
        "contract_type": contract_type,
        "strike": strike,
        "expiration": expiration,
        "dte": dte,
        "estimated_price": estimated_price,
        "stock_price": stock_price,
        "target": target,
        "stop": stop,
        "score": score,
        "sentiment": sentiment,
        "mentions": mentions,
        "risk": risk,
        "catalyst": catalyst,
        "thesis": thesis,
        "rationale": rationale,
        "rank": rank,
    }


def round_strike(strike: float, stock_price: float) -> float:
    """Round to a sensible options-chain strike spacing."""
    if stock_price < 25:
        step = 0.5
    elif stock_price < 200:
        step = 1.0
    else:
        step = 5.0
    return round(strike / step) * step


def simulate_close(estimated: float) -> float:
    """Return the closing premium for one contract given its open
    premium. Models a fat-tailed return distribution: roughly 52% win
    rate, mean return slightly positive, occasional total losses and
    occasional 3-5x winners."""
    # 8% chance of "total loss" (close ≈ 0.05 * entry) — the contract
    # decayed badly during the day.
    if RNG.random() < 0.08:
        return round(estimated * RNG.uniform(0.0, 0.15), 2)
    # 4% chance of "moonshot" (close 2.5-5x).
    if RNG.random() < 0.04:
        return round(estimated * RNG.uniform(2.5, 5.0), 2)
    # Otherwise normal-ish return centered slightly above 1.0.
    ret = RNG.gauss(1.02, 0.32)
    ret = max(0.10, min(2.5, ret))
    return round(estimated * ret, 2)


def main() -> None:
    today = dt.date(2026, 5, 8)
    start = today - dt.timedelta(days=365)
    days = trading_days(start, today)

    print(OUT_HEADER)

    trade_id_counter = 0
    execution_id_counter = 0
    trade_inserts: List[str] = []
    summary_inserts: List[str] = []
    execution_inserts: List[str] = []

    daily_basket_cap_usd = 500.0
    per_contract_cap_usd = 5.0

    for day in days:
        is_today = day == today
        date_str = day.isoformat()

        picks = [gen_pick(rank=i + 1, day=day) for i in range(10)]

        # Auto-executor walk: ranks 1..3 fitting in remaining $500 budget.
        remaining_budget = daily_basket_cap_usd
        executed_ranks: List[int] = []
        for p in picks:
            if p["rank"] > 3:
                break
            if p["estimated_price"] > per_contract_cap_usd:
                continue
            premium_total = p["estimated_price"] * 100
            if premium_total <= remaining_budget:
                executed_ranks.append(p["rank"])
                remaining_budget -= premium_total

        # Insert all 10 trade rows.
        day_trade_ids = []
        for p in picks:
            trade_id_counter += 1
            day_trade_ids.append(trade_id_counter)
            trade_inserts.append(
                "({tid}, '{date}', '{sym}', '{ct}', {strike}, '{exp}', {dte}, "
                "{est}, '{thesis}', {senti}, {stock}, {tgt}, {stop}, '{risk}', "
                "'{cat}', {mentions}, {rank}, {score}, '{rat}', 'claude-opus-4-7')".format(
                    tid=trade_id_counter,
                    date=date_str,
                    sym=p["symbol"],
                    ct=p["contract_type"],
                    strike=fmt_num(p["strike"]),
                    exp=p["expiration"],
                    dte=p["dte"],
                    est=fmt_num(p["estimated_price"]),
                    thesis=sql_escape(p["thesis"]),
                    senti=fmt_num(p["sentiment"], 3),
                    stock=fmt_num(p["stock_price"]),
                    tgt=fmt_num(p["target"]),
                    stop=fmt_num(p["stop"]),
                    risk=p["risk"],
                    cat=sql_escape(p["catalyst"]),
                    mentions=p["mentions"],
                    rank=p["rank"],
                    score=p["score"],
                    rat=sql_escape(p["rationale"]),
                )
            )

            # Summaries on every day except today.
            if not is_today:
                close_p = simulate_close(p["estimated_price"])
                stock_move = RNG.gauss(0, 0.018)
                stock_close = round(p["stock_price"] * (1 + stock_move), 2)
                summary_inserts.append(
                    "('{date}', '{sym}', '{ct}', {strike}, '{exp}', {entry}, "
                    "{close}, {sopen}, {sclose}, '')".format(
                        date=date_str, sym=p["symbol"], ct=p["contract_type"],
                        strike=fmt_num(p["strike"]), exp=p["expiration"],
                        entry=fmt_num(p["estimated_price"]),
                        close=fmt_num(close_p),
                        sopen=fmt_num(p["stock_price"]),
                        sclose=fmt_num(stock_close),
                    )
                )

        # Executions: open + close pair per executed rank.
        # Today's executions stay in 'holding' state so the new
        # green/red unrealized-P&L coloring activates on first boot.
        # Today is always live mode so the user sees real-position UX.
        for rank in executed_ranks:
            p = picks[rank - 1]
            tid = day_trade_ids[rank - 1]
            mode = "live" if is_today else RNG.choices(["live", "paper"], weights=[0.6, 0.4])[0]
            entry_fill = round(p["estimated_price"] * RNG.uniform(0.97, 1.03), 2)

            # OPEN side
            execution_id_counter += 1
            open_status = "filled"
            open_side_filled_at = f"'{date_str} 13:32:00+00'"  # ~9:32 ET
            execution_inserts.append(
                "({tid}, '{mode}', 'open', '{order}', '{status}', "
                "{fill}, 1, 1, '{date} 13:30:00+00', {filled_at}, '', "
                "'{date} 13:30:00+00')".format(
                    tid=tid, mode=mode, order=f"local-open-{execution_id_counter}",
                    status=open_status, fill=fmt_num(entry_fill),
                    date=date_str, filled_at=open_side_filled_at,
                )
            )

            # CLOSE side — present for past days only.
            if not is_today:
                execution_id_counter += 1
                close_p = simulate_close(p["estimated_price"])
                close_fill = round(close_p * RNG.uniform(0.97, 1.03), 2)
                execution_inserts.append(
                    "({tid}, '{mode}', 'close', '{order}', 'filled', "
                    "{fill}, 1, 1, '{date} 19:55:00+00', '{date} 19:56:00+00', '', "
                    "'{date} 19:55:00+00')".format(
                        tid=tid, mode=mode, order=f"local-close-{execution_id_counter}",
                        fill=fmt_num(close_fill), date=date_str,
                    )
                )

    # One big INSERT per table — Postgres handles thousands of rows in
    # a single statement without issue, and avoiding chunking keeps the
    # generator boring.
    if trade_inserts:
        print("INSERT INTO trades (id, date, symbol, contract_type, strike_price, expiration, dte, estimated_price, thesis, sentiment_score, current_price, target_price, stop_loss, risk_level, catalyst, mention_count, rank, score, rationale, model) VALUES")
        print(",\n".join(trade_inserts) + ";\n")

    if summary_inserts:
        print("INSERT INTO summaries (date, symbol, contract_type, strike_price, expiration, entry_price, closing_price, stock_open, stock_close, notes) VALUES")
        print(",\n".join(summary_inserts) + ";\n")

    if execution_inserts:
        print("INSERT INTO executions (trade_id, mode, side, schwab_order_id, status, fill_price, requested_quantity, filled_quantity, submitted_at, filled_at, error_message, created_at) VALUES")
        print(",\n".join(execution_inserts) + ";\n")

    # Re-sync the SERIAL sequences past the explicit IDs we inserted on
    # trades so future inserts don't collide. Other tables didn't get
    # explicit IDs, so nextval is already correct.
    print(f"SELECT setval(pg_get_serial_sequence('trades', 'id'), {trade_id_counter}, true);")

    print(OUT_FOOTER)


if __name__ == "__main__":
    main()
